### ISSUE TITLE
An idea to add NullCacheItem and NullCacheItemPool classes.

### ISSUE THREAD

**Issue by kuzmichus** [php-fig/cache#3]
I think it would be a good idea to add NullCacheItem and NullCacheItemPool classes for library developers as that in NullLogger from PSR-3.

**Comment by aequasi** [comment]
This is an implementation issue, not a interface/PSR issue

**Comment by ThaDafinser** [comment]
This is ***not an implementation issue***. 
The `NullLogger` is awesome, since you dont have to deal with `null` values everywhere. 
You always got an instanceof the CacheItem!

Please add the Null object this in the next major version
https://github.com/php-fig/log/tree/master/Psr/Log

**Comment by aequasi** [comment]
Any implementation of PSR-6 Can implement a `NullLogger` themselves. There will never be a "next major version` of this repository.

***For Example/Shameless Plug: https://github.com/php-cache/void-adapter***

**Comment by vitortd** [comment]
This repo only has _specification code_ meaning you should not add any kind of implementation.
For instance, the `CacheItemInterface` should be only an interface to be used for implementors like in a contract, a protocol.
It's out of the scope implementing a `NullCacheItem` here, since implementors that want to provide it should implement the interface `CacheItemInterface`.

**Comment by lightningspirit** [comment]
This repo only has specification code meaning you should not add any kind of implementation.
For instance, the `CacheItemInterface` should be only an interface to be used for implementors like in a contract, a protocol.
It's out of the scope implementing a `NullCacheItem` here, since implementors that want to provide it should implement the interface `CacheItemInterface`.

**Comment by ThaDafinser** [comment]
Why then `psr/log` got the `NullLogger`? Because its very useful!

@aequasi i know there are packages around which provide that. But that doesn't change anything, since in the composer dependencies you may want only to depend on this package and let the user choose their caching implementation.

With a Null object a lot of things get easier, but without the object in this repo you cant do it
http://designpatternsphp.readthedocs.org/en/latest/Behavioral/NullObject/README.html

If there is no intention to include it, ***i will create another package with just a NullCacheItem and NullCacheItemPool***

**Comment by aequasi** [comment]
There will be no intention to include it. This repository is frozen for new features.

**Comment by peregrinphp** [comment]
@ ThaDafinser  similar to the package already exists: https://github.com/php-fig/cache-util

**Comment by ThaDafinser** [comment]
@peregrinphp it does not got a NullCacheItem, so not useful

**Comment by Crell** [comment]
PSR-3 included both the interfaces of the specification and some utilities in the spec itself. In hindsight, that was a mistake and we should not have done so, since the utilities could evolve over time but the spec itself by definition should not.

For PSR-6, we split the utilities off to a separate util library, which @peregrinphp linked to. The spec (this repo) is fixed and will not change, period, until and unless FIG produces a 2.0 version of the spec (not anytime soon).  The util library, though, welcomes pull requests with improvements as long as it doesn't veer into building a real production implementation.  A simple null implementation PR would be welcomed there (subject to review, etc. of course).

**Comment by ThaDafinser** [comment]
@Crell i'm sorry, but i can't use the current `cache-util` package

Major missing things
- a stable release/tag, not only a branch (with semver)
- build/check services (travis, scrutinizer e.g.)
- tests for all traits/classes

The release + build/check services can only be done by the package owner.
The tests could be improved by a "external" contribution.

After that adding a `NullObject` may makes sense

**Comment by Crell** [comment]
@ThaDafinser Let me summarize what you just said, since I doubt it came off as you intended: 

"Here's work you need to do, but I refuse to help with it until you do this other unrelated work. Until then you can't have my ball."

Suit yourself.  IF FIG releases a Null implementation of PSR-6, it will live in cache-util (which has a couple of open issues that could use assistance), but not until someone writes it.  If you don't like cache-util, OK, you can release your own Null implementation package elsewhere.  That's totally fine, totally compatible, and the entire point of having PSR standards. :-)  I'm just letting you know where to contribute if you feel like collaborating. 

But as such code will never, ever live in the cache repository, this thread serves no further purpose.
